In [17]:
##Importing the Data
import pandas as pd
df = pd.read_csv(r'C:\Users\Pavlo\Documents\Python Practice Files\pokemon_data.csv')
print(df.head())

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False

In [13]:
##Reading headers
#print(df.columns)

##Reading each column
#print(df[['Name', 'Type 1', 'HP']])

##Read Each Row
#print(df.iloc[0:4])

##Read a specific location (R,C)
#print(df.iloc[2,1])

##Shows data on specific filter
#df.loc[df["Type 1"] == 'Fire']

In [2]:
##Describes the data set
df.describe()

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [8]:
##Sorting the Data
#df.sort_values("Name")
#df.sort_values("Name", ascending = False)
df.sort_values(["Type 1", "HP"])

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
316,292,Shedinja,Bug,Ghost,1,90,45,30,30,40,3,False
230,213,Shuckle,Bug,Rock,20,10,230,10,230,5,2,False
462,415,Combee,Bug,Flying,30,30,42,30,42,70,4,False
603,543,Venipede,Bug,Poison,30,45,59,30,39,57,5,False
314,290,Nincada,Bug,Ground,31,45,90,30,30,40,3,False
51,46,Paras,Bug,Grass,35,70,55,45,55,25,1,False
446,401,Kricketot,Bug,NaN,37,25,41,25,41,25,4,False
732,664,Scatterbug,Bug,NaN,38,35,40,27,25,35,6,False
16,13,Weedle,Bug,Poison,40,35,30,20,20,50,1,False
179,165,Ledyba,Bug,Flying,40,20,30,40,80,55,2,False
181,167,Spinarak,Bug,Poison,40,60,40,40,40,30,2,False
307,283,Surskit,Bug,Water,40,30,32,50,52,65,3,False
457,412,Burmy,Bug,NaN,40,29,45,29,45,36,4,False
604,544,Whirlipede,Bug,Poison,40,55,99,40,79,47,5,False
13,10,Caterpie,Bug,NaN,45,30,35,20,20,45,1,False
17,14,Kakuna,Bug,Poison,45,25,50,25,25,35,1,False
288,265,Wurmple,Bug,NaN,45,45,35,20,30,20,3,False
600,540,Sewaddle,Bug,Grass,45,53,70,40,60,42,5,False
733,665,Spewpa,Bug,NaN,45,22,60,27,30,29,6,False
14,11,Metapod,Bug,NaN,50,20,55,25,25,30,1,False
219,204,Pineco,Bug,NaN,50,65,90,35,35,15,2,False
289,266,Silcoon,Bug,NaN,50,35,55,25,25,15,3,False
291,268,Cascoon,Bug,NaN,50,35,55,25,25,15,3,False
618,557,Dwebble,Bug,Rock,50,65,85,35,35,55,5,False
649,588,Karrablast,Bug,NaN,50,75,45,40,45,60,5,False
656,595,Joltik,Bug,Electric,50,47,50,57,50,65,5,False
677,616,Shelmet,Bug,NaN,50,40,85,40,65,25,5,False
180,166,Ledian,Bug,Flying,55,35,50,55,110,85,2,False
601,541,Swadloon,Bug,Grass,55,63,90,50,80,42,5,False
697,636,Larvesta,Bug,Fire,55,85,55,50,55,60,5,False
...,...,...,...,...,...,...,...,...,...,...,...,...
201,186,Politoed,Water,NaN,90,75,75,90,100,70,2,False
541,484,Palkia,Water,Dragon,90,120,100,150,120,100,4,True
713,647,KeldeoOrdinary Forme,Water,Fighting,91,72,90,129,90,108,5,False
714,647,KeldeoResolute Forme,Water,Fighting,91,72,90,129,90,108,5,False
86,80,Slowbro,Water,Psychic,95,75,110,100,80,30,1,False
87,80,SlowbroMega Slowbro,Water,Psychic,95,75,180,130,80,30,1,False
140,130,Gyarados,Water,Flying,95,125,79,60,100,81,1,False
141,130,GyaradosMega Gyarados,Water,Dark,95,155,109,70,130,81,1,False
210,195,Quagsire,Water,Ground,95,85,85,65,65,35,2,False
214,199,Slowking,Water,Psychic,95,75,80,100,110,30,2,False
382,350,Milotic,Water,NaN,95,60,79,100,125,81,3,False
562,503,Samurott,Water,NaN,95,100,85,108,70,70,5,False
199,184,Azumarill,Water,Fairy,100,50,80,60,80,50,2,False
264,245,Suicune,Water,NaN,100,75,115,90,115,85,2,True
282,260,Swampert,Water,Ground,100,110,90,85,90,60,3,False
283,260,SwampertMega Swampert,Water,Ground,100,150,110,95,110,70,3,False
404,369,Relicanth,Water,Rock,100,90,130,45,65,55,3,False
421,382,Kyogre,Water,NaN,100,100,90,150,140,90,3,True
422,382,KyogrePrimal Kyogre,Water,NaN,100,150,90,180,160,90,3,True
548,490,Manaphy,Water,NaN,100,100,100,100,100,100,4,False
654,593,Jellicent,Water,Ghost,100,60,70,85,105,60,5,False
597,537,Seismitoad,Water,Ground,105,95,75,85,75,74,5,False
372,340,Whiscash,Water,Ground,110,78,73,76,71,60,3,False
470,423,Gastrodon,Water,Ground,111,83,68,92,82,39,4,False
185,171,Lanturn,Water,Electric,125,58,58,76,76,67,2,False
142,131,Lapras,Water,Ice,130,85,80,85,95,60,1,False
145,134,Vaporeon,Water,NaN,130,65,60,110,95,65,1,False
350,320,Wailmer,Water,NaN,130,70,35,70,35,60,3,False
655,594,Alomomola,Water,NaN,165,75,80,40,45,65,5,False
351,321,Wailord,Water,NaN,170,90,45,90,45,60,3,False

In [10]:
##Making changes
#df["Total"] = df["HP"] + df["Attack"] + df["Defense"] + df["Sp. Atk"] + df["Sp. Def"] + df["Speed"]
##Making the change disappear
#df = df.drop(columns = ["Total"])

df["Total"] = df.iloc[:, 4:10].sum(axis = 1)
cols = list(df.columns)
df = df[cols[0:4] + [cols[-1]] + cols[4:12]]

df.head(5)

,#,Name,Type 1,Type 2,Legendary,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
0,1,Bulbasaur,Grass,Poison,False,591,45,49,49,65,65,45,1
1,2,Ivysaur,Grass,Poison,False,750,60,62,63,80,80,60,1
2,3,Venusaur,Grass,Poison,False,970,80,82,83,100,100,80,1
3,3,VenusaurMega Venusaur,Grass,Poison,False,1170,80,100,123,122,120,80,1
4,4,Charmander,Fire,NaN,False,553,39,52,43,60,50,65,1